
-- ACTIVIDAD 5

-- CONSULTAS DE ACTUALIZACIÓN
-- Objetivo de la actividad:
-- Elaboración de Consultas (QUERIES) de Actualización en SQL. Mostrar el Código SQL y
-- los resultados.

-- SOLUCIONES
-- 1.- EXPLIQUE LA FUNCIÓN Y EL FORMATO EN LENGUAJE SQL DE LAS INSTRUCCIONES
-- PARA:
-- INSERTAR DATOS: Función para insertar datos en una tabla.
-- INSERT INTO NOMBRE_TABLA (CAMPO1, CAMPO2, CAMPO3, CAMPO4) VALUES (VALOR1, VALOR2, VALOR3, VALOR4);

-- MODIFICACIÓN DE DATOS: Función para modificar datos en una tabla.
-- UPDATE NOMBRE_TABLA SET CAMPO1 = VALOR1, CAMPO2 = VALOR2, CAMPO3 = VALOR3, CAMPO4 = VALOR4 WHERE CONDICION;

-- ELIMINAR DATOS: Función para eliminar datos en una tabla.
-- DELETE FROM NOMBRE_TABLA WHERE CONDICION;

-- MODIFICAR LA ESTRUCTURA DE LA BASE DE DATOS: Función para modificar la estructura de una tabla.
-- ALTER TABLE NOMBRE_TABLA ADD CAMPO1 TIPO_DATO;
-- ALTER TABLE NOMBRE_TABLA DROP CAMPO1;
-- ALTER TABLE NOMBRE_TABLA MODIFY CAMPO1 TIPO_DATO;
-- ALTER TABLE NOMBRE_TABLA RENAME TO NUEVO_NOMBRE_TABLA;

-- ELIMINAR LA ESTRUCTURA DE LA BASE DE DATOS: Función para eliminar la estructura de una tabla.
-- DROP TABLE NOMBRE_TABLA;

-- 2.- DAR DE ALTA LOS SIGUIENTES PROVEEDORES:
-- NÚMERO S20 , PALAZUELOS ,DE LA CIUDAD VENEZUELA, CON STATUS 10 .
-- NUMERO S18 , CORTEZ ,DE LA CIUDAD BUENOS AIRES, CON STATUS 20 .
-- NUMERO S19 , SINATRA ,DE LA CIUDAD ‘NUEVA YORK’, CON STATUS 10 .
INSERT INTO PROVEEDOR (NUMEROPROV, NOMBRE, CIUDAD, ESTATUS) VALUES ('S20', 'PALAZUELOS', 'VENEZUELA', 10);
INSERT INTO PROVEEDOR (NUMEROPROV, NOMBRE, CIUDAD, ESTATUS) VALUES ('S18', 'CORTEZ', 'BUENOS AIRES', 20);
INSERT INTO PROVEEDOR (NUMEROPROV, NOMBRE, CIUDAD, ESTATUS) VALUES ('S19', 'SINATRA', 'NUEVA YORK', 10);

-- 3.- MODIFICAR A TODOS LOS PROVEEDORES DE LA CIUDAD MEXICO Y PONERLE CDMX.
UPDATE PROVEEDOR SET CIUDAD = 'CDMX' WHERE CIUDAD = 'MEXICO';

--  4.- AUMENTAR UN 10 % AL COSTO DE LOS PRODUCTOS DE COLOR AZUL.
UPDATE PARTES SET COSTO = COSTO * 1.1 WHERE COLOR = 'AZUL';

--  5.- ELIMINAR LOS PEDIDOS DE LA TABLA COMPRAS, SI EL PROVEEDOR ES S2.
DELETE FROM COMPRAS WHERE NUMEROPROV = 'S2';

-- 6.- ELIMINAR TODOS LOS PEDIDOS DE LA TABLA COMPRAS.
DELETE FROM COMPRAS;
