export 'package:clase63/screens/alert_screen.dart';
export 'package:clase63/screens/card_screen.dart';
export 'package:clase63/screens/listview2_screen.dart';
export 'package:clase63/screens/home_screen.dart';
export 'package:clase63/router/app_routes.dart';
export 'package:clase63/screens/listview1_screen.dart';
export 'package:clase63/screens/avatar_screen.dart';
export 'package:clase63/screens/animated_screen.dart';
export 'package:clase63/screens/inputs_screen.dart';
