/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package punto3_S_GR.Vista;

import javax.swing.JOptionPane;

import punto3_S_GR.Controlador.Controlador;
import punto3_S_GR.Modelo.Circulo;
import punto3_S_GR.Modelo.Cuadrado;
import punto3_S_GR.Modelo.Triangulo;

/**
 *
 * @author User
 */
public class CrearFigura extends javax.swing.JFrame {
    
    private Controlador c;

    /**
     * Creates new form CrearFigura
     */
    public CrearFigura(Controlador c) {
        this.c = c;
        initComponents();
        
        panelCirculo.setVisible(false);
        panelCuadrado.setVisible(false);
        panelTriangulo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cmbPrincipal = new javax.swing.JComboBox<>();
        panelCuadrado = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCuadradoLado = new javax.swing.JTextField();
        panelCirculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCirculo = new javax.swing.JTextField();
        panelTriangulo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTrianguloLado2 = new javax.swing.JTextField();
        txtTrianguloBase = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Tipo:");

        cmbPrincipal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Circulo", "Cuadrado", "Triangulo" }));
        cmbPrincipal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPrincipalItemStateChanged(evt);
            }
        });

        jLabel4.setText("Lado:");

        javax.swing.GroupLayout panelCuadradoLayout = new javax.swing.GroupLayout(panelCuadrado);
        panelCuadrado.setLayout(panelCuadradoLayout);
        panelCuadradoLayout.setHorizontalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtCuadradoLado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCuadradoLayout.setVerticalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCuadradoLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel1.setText("Radio: ");

        javax.swing.GroupLayout panelCirculoLayout = new javax.swing.GroupLayout(panelCirculo);
        panelCirculo.setLayout(panelCirculoLayout);
        panelCirculoLayout.setHorizontalGroup(
            panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCirculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelCirculoLayout.setVerticalGroup(
            panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCirculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel5.setText("Altura:");

        jLabel6.setText("Base:");

        javax.swing.GroupLayout panelTrianguloLayout = new javax.swing.GroupLayout(panelTriangulo);
        panelTriangulo.setLayout(panelTrianguloLayout);
        panelTrianguloLayout.setHorizontalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTrianguloLado2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrianguloBase, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        panelTrianguloLayout.setVerticalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrianguloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTrianguloBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTrianguloLado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnIngresar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(panelCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPrincipalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPrincipalItemStateChanged
        // ComboBox
        // Mostrar el panel correspondiente
        if (cmbPrincipal.getSelectedIndex() == 1) {
            panelCirculo.setVisible(true);
            panelCuadrado.setVisible(false);
            panelTriangulo.setVisible(false);
        } else if (cmbPrincipal.getSelectedIndex() == 2) {
            panelCirculo.setVisible(false);
            panelCuadrado.setVisible(true);
            panelTriangulo.setVisible(false);
        } else if (cmbPrincipal.getSelectedIndex() == 3) {
            panelCirculo.setVisible(false);
            panelCuadrado.setVisible(false);
            panelTriangulo.setVisible(true);
        }
    }//GEN-LAST:event_cmbPrincipalItemStateChanged

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // Boton Ingresar
        // Validar que se haya ingresado un valor
        if (cmbPrincipal.getSelectedIndex() == 1) {
            if (txtCirculo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un valor para el radio", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Validar que el valor sea un numero
            try {
                Double.parseDouble(txtCirculo.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El valor ingresado no es un numero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Validar que el valor sea mayor a 0
            if (Double.parseDouble(txtCirculo.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "El valor ingresado no es mayor a 0", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } else if (cmbPrincipal.getSelectedIndex() == 2) {
            if (txtCuadradoLado.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un valor para el lado", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Validar que el valor sea un numero
            try {
                Double.parseDouble(txtCuadradoLado.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El valor ingresado no es un numero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Validar que el valor sea mayor a 0
            if (Double.parseDouble(txtCuadradoLado.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "El valor ingresado no es mayor a 0", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } else if (cmbPrincipal.getSelectedIndex() == 3) {
            if (txtTrianguloBase.getText().isEmpty() || txtTrianguloLado2.getText().isEmpty() ){
                JOptionPane.showMessageDialog(this, "Ingrese un valor para los lados", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Validar que el valor sea un numero
            try {
                Double.parseDouble(txtTrianguloBase.getText());
                Double.parseDouble(txtTrianguloLado2.getText());

                // Verificar que sea un triangulo valido
                if (Double.parseDouble(txtTrianguloBase.getText()) + Double.parseDouble(txtTrianguloLado2.getText()) <= Double.parseDouble(txtTrianguloLado2.getText())) {
                    JOptionPane.showMessageDialog(this, "Los lados ingresados no forman un triangulo", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El valor ingresado no es un numero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Validar que el valor sea mayor a 0
            if (Double.parseDouble(txtTrianguloBase.getText()) <= 0 || Double.parseDouble(txtTrianguloLado2.getText()) <= 0 ) {
                JOptionPane.showMessageDialog(this, "El valor ingresado no es mayor a 0", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Agregar el objeto al arreglo
        if (cmbPrincipal.getSelectedIndex() == 1) {
            Circulo circle = new Circulo("Circulo", Double.parseDouble(txtCirculo.getText()));
            c.agregarFigura(circle);
        } else if (cmbPrincipal.getSelectedIndex() == 2) {
            Cuadrado square = new Cuadrado("Cuadrado", Double.parseDouble(txtCuadradoLado.getText()));
            c.agregarFigura(square);
        } else if (cmbPrincipal.getSelectedIndex() == 3) {
            Triangulo rectangle = new Triangulo("Triangulo", Double.parseDouble(txtTrianguloBase.getText()), Double.parseDouble(txtTrianguloLado2.getText()));
            c.agregarFigura(rectangle);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una opcion", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Actualizar la tabla
        c.tablaFiguras.actualizarTabla();

        // Cerrar la ventana
        this.dispose();

    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cmbPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelCirculo;
    private javax.swing.JPanel panelCuadrado;
    private javax.swing.JPanel panelTriangulo;
    private javax.swing.JTextField txtCirculo;
    private javax.swing.JTextField txtCuadradoLado;
    private javax.swing.JTextField txtTrianguloBase;
    private javax.swing.JTextField txtTrianguloLado2;
    // End of variables declaration//GEN-END:variables
}
