/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.ClienteDao;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge Alberto
 */
public class Sistema extends javax.swing.JFrame {
 Cliente cl = new Cliente();
    ClienteDao client = new ClienteDao();
    /**
     * Creates new form Sistema
     */
    public Sistema() {
           setIconImage(new ImageIcon(getClass().getResource("/Img/LOGOPRINCIPAL.png")).getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        txtAPC = new javax.swing.JTextField();
        txtAMC = new javax.swing.JTextField();
        txtNomC = new javax.swing.JTextField();
        txtCalleC = new javax.swing.JTextField();
        txtNumC = new javax.swing.JTextField();
        txtColC = new javax.swing.JTextField();
        txtCPC = new javax.swing.JTextField();
        txtCiuC = new javax.swing.JTextField();
        txtEstC = new javax.swing.JTextField();
        txtPaisC = new javax.swing.JTextField();
        txtTelC = new javax.swing.JTextField();
        txtCorreoC = new javax.swing.JTextField();
        btnGuardarC = new javax.swing.JButton();
        btnEliminarC = new javax.swing.JButton();
        btnActualizarC = new javax.swing.JButton();
        btnNuevoC = new javax.swing.JButton();
        txtIdCliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCliente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtCodPro = new javax.swing.JTextField();
        txtEmpresaPro = new javax.swing.JTextField();
        txtTelPro = new javax.swing.JTextField();
        txtCallePro = new javax.swing.JTextField();
        txtNumPro = new javax.swing.JTextField();
        txtColPro = new javax.swing.JTextField();
        txtCiuPro = new javax.swing.JTextField();
        txtEstadoPro = new javax.swing.JTextField();
        txtCPPRO = new javax.swing.JTextField();
        txtPaisPro = new javax.swing.JTextField();
        btnGuardarPro = new javax.swing.JButton();
        btnEliminarPro = new javax.swing.JButton();
        btnActualizarPro = new javax.swing.JButton();
        btnNuevoPro = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableProveedor = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtCodProduc = new javax.swing.JTextField();
        txtNomProduc = new javax.swing.JTextField();
        txtCanProduc = new javax.swing.JTextField();
        txtPrecioProduc = new javax.swing.JTextField();
        cbProvedorProduc = new javax.swing.JComboBox<>();
        btnGuardarProduc = new javax.swing.JButton();
        btnEliminarProduc = new javax.swing.JButton();
        btnActualizarProduc = new javax.swing.JButton();
        btnNuevoProduc = new javax.swing.JButton();
        btnExcelProduc = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableProducto = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableVentas = new javax.swing.JTable();
        btnPDFVentas = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        btnRegistrarUsu = new javax.swing.JButton();
        txtAPUsu = new javax.swing.JTextField();
        txtAMUsu = new javax.swing.JTextField();
        txtNomUsu = new javax.swing.JTextField();
        txtCorreoUsu = new javax.swing.JTextField();
        txtContraseñaUsu = new javax.swing.JTextField();
        cbRolUsu = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEliminarVenta = new javax.swing.JButton();
        txtCodigoVenta = new javax.swing.JTextField();
        txtDescripcionVenta = new javax.swing.JTextField();
        txtCantidadVenta = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtStockDisponible = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableVenta = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodVentaCliente = new javax.swing.JTextField();
        txtNomClienteVenta = new javax.swing.JTextField();
        btnGenerarVenta = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtCodEmp = new javax.swing.JTextField();
        txtNomEmp = new javax.swing.JTextField();
        txtTelEmp = new javax.swing.JTextField();
        txtCalleEmp = new javax.swing.JTextField();
        txtNumEmp = new javax.swing.JTextField();
        txtColEmp = new javax.swing.JTextField();
        txtCiuEmp = new javax.swing.JTextField();
        txtCPEmp = new javax.swing.JTextField();
        txtEstadoEmp = new javax.swing.JTextField();
        txtPaisEmp = new javax.swing.JTextField();
        txtMenEmp = new javax.swing.JTextField();
        btnActualizarEmp = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Nventa.png"))); // NOI18N
        jButton1.setText("NUEVA VENTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Clientes.png"))); // NOI18N
        jButton2.setText("CLIENTES");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 170, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/proveedor.png"))); // NOI18N
        jButton3.setText("PROVEEDOR");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 170, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/producto.png"))); // NOI18N
        jButton4.setText("PRODUCTOS");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 170, 40));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/compras.png"))); // NOI18N
        jButton5.setText("VENTAS");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 170, 40));

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/config.png"))); // NOI18N
        jButton6.setText("CONFIGURACIÓN");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 170, -1));

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Clientes.png"))); // NOI18N
        jButton7.setText("USUARIOS");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LOGOPRINCIPALL.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DETAILER´S ACOSTA.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 990, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "CLIENTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("CALLE:");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("NUMERO EXTERIOR O INTERIOR:");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("COLONIA:");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("CODIGO POSTAL:");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("CIUDAD:");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("ESTADO:");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("PAIS:");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("TELEFONO:");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("CORREO ELECTRONICO:");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("NOMBRE:");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("APELLIDO MATERNO:");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("APELLIDO PATERNO:");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("CODIGO:");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtCodCliente.setText("jTextField8");
        jPanel9.add(txtCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, -1));

        txtAPC.setText("jTextField9");
        jPanel9.add(txtAPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 150, -1));

        txtAMC.setText("jTextField10");
        jPanel9.add(txtAMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 120, -1));

        txtNomC.setText("jTextField11");
        jPanel9.add(txtNomC, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 170, -1));

        txtCalleC.setText("jTextField12");
        jPanel9.add(txtCalleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));

        txtNumC.setText("jTextField13");
        jPanel9.add(txtNumC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        txtColC.setText("jTextField14");
        jPanel9.add(txtColC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 130, -1));

        txtCPC.setText("jTextField16");
        jPanel9.add(txtCPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        txtCiuC.setText("jTextField17");
        jPanel9.add(txtCiuC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 150, -1));

        txtEstC.setText("jTextField18");
        jPanel9.add(txtEstC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 130, -1));

        txtPaisC.setText("jTextField19");
        jPanel9.add(txtPaisC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 170, -1));

        txtTelC.setText("jTextField20");
        jPanel9.add(txtTelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 150, -1));

        txtCorreoC.setText("jTextField21");
        jPanel9.add(txtCorreoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 200, -1));

        btnGuardarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        btnGuardarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarCMouseClicked(evt);
            }
        });
        btnGuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCActionPerformed(evt);
            }
        });
        jPanel9.add(btnGuardarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 50, 40));

        btnEliminarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(btnEliminarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 50, 40));

        btnActualizarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnActualizarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(btnActualizarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 50, 40));

        btnNuevoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnNuevoC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(btnNuevoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 50, 40));

        txtIdCliente.setText("jTextField1");
        jPanel9.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 40, -1));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 390));

        TableCliente.setBackground(new java.awt.Color(255, 0, 0));
        TableCliente.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        TableCliente.setForeground(new java.awt.Color(0, 0, 0));
        TableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "COD", "AP_P", "AP_M", "NOM", "CALLE", "NU EXT/INT", "COL", "CIUDAD", "CP", "ESTADO", "PAIS", "TEL", "CORREO"
            }
        ));
        jScrollPane2.setViewportView(TableCliente);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 460, 280));

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "PROVEEDORES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 36), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("CODIGO:");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("EMPRESA:");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("TELEFONO:");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("CALLE:");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("NUMERO EXTERIOR/INTERIOR:");
        jPanel10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("COLONIA:");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("CIUDAD:");
        jPanel10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("ESTADO:");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("CODIGO POSTAL:");
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("PAIS:");
        jPanel10.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txtCodPro.setText("jTextField15");
        jPanel10.add(txtCodPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 100, -1));

        txtEmpresaPro.setText("jTextField22");
        jPanel10.add(txtEmpresaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 120, -1));

        txtTelPro.setText("jTextField23");
        txtTelPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelProActionPerformed(evt);
            }
        });
        jPanel10.add(txtTelPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 130, -1));

        txtCallePro.setText("jTextField24");
        jPanel10.add(txtCallePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 110, 120, -1));

        txtNumPro.setText("jTextField25");
        jPanel10.add(txtNumPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 160, -1));

        txtColPro.setText("jTextField26");
        jPanel10.add(txtColPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 120, -1));

        txtCiuPro.setText("jTextField27");
        txtCiuPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiuProActionPerformed(evt);
            }
        });
        jPanel10.add(txtCiuPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 120, -1));

        txtEstadoPro.setText("jTextField28");
        jPanel10.add(txtEstadoPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 110, -1));

        txtCPPRO.setText("jTextField29");
        jPanel10.add(txtCPPRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, -1));

        txtPaisPro.setText("jTextField30");
        jPanel10.add(txtPaisPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 90, -1));

        btnGuardarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        jPanel10.add(btnGuardarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 60, 50));

        btnEliminarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        jPanel10.add(btnEliminarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 60, 50));

        btnActualizarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        jPanel10.add(btnActualizarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 60, 50));

        btnNuevoPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        jPanel10.add(btnNuevoPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 60, 50));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 394));

        TableProveedor.setBackground(new java.awt.Color(255, 0, 0));
        TableProveedor.setForeground(new java.awt.Color(0, 0, 0));
        TableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "COD", "EMPRESA", "TEL", "CALLE", "NUMEXTINT", "COL", "CIUD", "CP", "EST", "PAIS"
            }
        ));
        jScrollPane3.setViewportView(TableProveedor);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 560, 360));

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "PRODUCTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 0, 0));
        jLabel35.setText("CODIGO:");
        jPanel11.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel36.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 0, 0));
        jLabel36.setText("NOMBRE:");
        jPanel11.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel37.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 0, 0));
        jLabel37.setText("CANTIDAD:");
        jPanel11.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel38.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 0, 0));
        jLabel38.setText("PRECIO:");
        jPanel11.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel39.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 0, 0));
        jLabel39.setText("PROVEEDOR:");
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        txtCodProduc.setText("jTextField31");
        jPanel11.add(txtCodProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        txtNomProduc.setText("jTextField32");
        jPanel11.add(txtNomProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 190, -1));

        txtCanProduc.setText("jTextField33");
        jPanel11.add(txtCanProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, -1));

        txtPrecioProduc.setText("jTextField34");
        jPanel11.add(txtPrecioProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, -1));

        cbProvedorProduc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel11.add(cbProvedorProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 210, -1));

        btnGuardarProduc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        jPanel11.add(btnGuardarProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 273, 50, 40));

        btnEliminarProduc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        jPanel11.add(btnEliminarProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 269, 50, 40));

        btnActualizarProduc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        jPanel11.add(btnActualizarProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 272, 50, 40));

        btnNuevoProduc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        jPanel11.add(btnNuevoProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 333, 50, 40));

        btnExcelProduc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/excel.png"))); // NOI18N
        jPanel11.add(btnExcelProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 331, 50, 40));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 390));

        TableProducto.setBackground(new java.awt.Color(255, 0, 0));
        TableProducto.setForeground(new java.awt.Color(0, 0, 0));
        TableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "STOCK", "PRECIO", "PROVEEDOR"
            }
        ));
        jScrollPane4.setViewportView(TableProducto);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 590, 320));

        jTabbedPane1.addTab("tab4", jPanel5);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableVentas.setBackground(new java.awt.Color(255, 0, 0));
        TableVentas.setForeground(new java.awt.Color(0, 0, 0));
        TableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CLIENTE", "APELLIDOPVENDEDOR", "APELLIDOMVENDEDOR", "NOMBREVENDEDOR", "TOTAL"
            }
        ));
        jScrollPane5.setViewportView(TableVentas);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 990, 300));

        btnPDFVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pdf.png"))); // NOI18N
        jPanel7.add(btnPDFVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 22, 60, 40));

        jTabbedPane1.addTab("tab6", jPanel7);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "USUARIOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 0, 0));
        jLabel51.setText("APELLIDO PATERNO:");
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel52.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 0, 0));
        jLabel52.setText("APELLIDO MATERNO:");
        jPanel13.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel53.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 0, 0));
        jLabel53.setText("NOMBRE:");
        jPanel13.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel54.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 0, 0));
        jLabel54.setText("CORREO ELECTRONICO:");
        jPanel13.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel55.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 0, 0));
        jLabel55.setText("CONTRASEÑA:");
        jPanel13.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel56.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 0, 0));
        jLabel56.setText("ROL:");
        jPanel13.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        btnRegistrarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        btnRegistrarUsu.setText("REGISTRAR");
        jPanel13.add(btnRegistrarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 170, 40));

        txtAPUsu.setText("jTextField46");
        jPanel13.add(txtAPUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 270, -1));

        txtAMUsu.setText("jTextField47");
        jPanel13.add(txtAMUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 230, -1));

        txtNomUsu.setText("jTextField48");
        jPanel13.add(txtNomUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 320, -1));

        txtCorreoUsu.setText("jTextField49");
        jPanel13.add(txtCorreoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 240, -1));

        txtContraseñaUsu.setText("jTextField50");
        jPanel13.add(txtContraseñaUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 260, -1));

        cbRolUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel13.add(cbRolUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 280, -1));

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 394));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "APELLIDOP", "APELLIDOM", "NOMBRE", "CORREO", "CONTRASEÑA", "ROL"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 520, 230));

        jTabbedPane1.addTab("tab5", jPanel6);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("CODIGO PRODUCTO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("DESCRIPCIÓN");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("CANTIDAD");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("PRECIO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("STOCK");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        btnEliminarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        jPanel2.add(btnEliminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));
        jPanel2.add(txtCodigoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 57, 140, -1));
        jPanel2.add(txtDescripcionVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 110, -1));
        jPanel2.add(txtCantidadVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 70, -1));
        jPanel2.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 70, -1));
        jPanel2.add(txtStockDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 70, -1));

        TableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCIÓN", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(TableVenta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 950, 170));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("CODIGO CLIENTE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("NOMBRE");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));
        jPanel2.add(txtCodVentaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, -1));

        txtNomClienteVenta.setEditable(false);
        jPanel2.add(txtNomClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 240, -1));

        btnGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/print.png"))); // NOI18N
        jPanel2.add(btnGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/money.png"))); // NOI18N
        jLabel10.setText("TOTAL A PAGAR:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        LabelTotal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LabelTotal.setForeground(new java.awt.Color(255, 0, 0));
        LabelTotal.setText(".....");
        jPanel2.add(LabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 110, -1));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "CONFIGURACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 0, 0));
        jLabel40.setText("CODIGO:");
        jPanel12.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel41.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setText("CALLE:");
        jPanel12.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel42.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 0, 0));
        jLabel42.setText("CIUDAD:");
        jPanel12.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 0, 0));
        jLabel43.setText("NOMBRE:");
        jPanel12.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 0, 0));
        jLabel44.setText("TELEFONO:");
        jPanel12.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel45.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 0, 0));
        jLabel45.setText("NUM_EXT/INT:");
        jPanel12.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabel46.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 0, 0));
        jLabel46.setText("COLONIA:");
        jPanel12.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jLabel47.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 0, 0));
        jLabel47.setText("CODIGO POSTAL:");
        jPanel12.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jLabel48.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 0, 0));
        jLabel48.setText("ESTADO:");
        jPanel12.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 0, 0));
        jLabel49.setText("PAIS:");
        jPanel12.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 0, 0));
        jLabel50.setText("MENSAJE:");
        jPanel12.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        txtCodEmp.setText("jTextField35");
        jPanel12.add(txtCodEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 100, -1));

        txtNomEmp.setText("jTextField36");
        jPanel12.add(txtNomEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 120, -1));

        txtTelEmp.setText("jTextField37");
        jPanel12.add(txtTelEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 130, -1));

        txtCalleEmp.setText("jTextField38");
        jPanel12.add(txtCalleEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 120, -1));

        txtNumEmp.setText("jTextField39");
        jPanel12.add(txtNumEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        txtColEmp.setText("jTextField40");
        jPanel12.add(txtColEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 140, -1));

        txtCiuEmp.setText("jTextField41");
        jPanel12.add(txtCiuEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, -1));

        txtCPEmp.setText("jTextField42");
        jPanel12.add(txtCPEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        txtEstadoEmp.setText("jTextField43");
        jPanel12.add(txtEstadoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 120, -1));

        txtPaisEmp.setText("jTextField44");
        jPanel12.add(txtPaisEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 130, -1));

        txtMenEmp.setText("jTextField45");
        jPanel12.add(txtMenEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 260, -1));

        btnActualizarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnActualizarEmp.setText("ACTUALIZAR");
        jPanel12.add(btnActualizarEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 210, 40));

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 670, 390));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LOGOPRINCIPAL.png"))); // NOI18N
        jPanel8.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        jTabbedPane1.addTab("tab7", jPanel8);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 1030, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCiuProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiuProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiuProActionPerformed

    private void txtTelProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelProActionPerformed

    private void btnGuardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCActionPerformed
        // TODO add your handling code here:
         if (!"".equals(txtCodCliente.getText()) || !"".equals(txtAPC.getText()) || !"".equals(txtAMC.getText())|| !"".equals(txtNomC.getText())|| !"".equals(txtCalleC.getText()) || !"".equals(txtNumC.getText())|| !"".equals(txtColC.getText())|| !"".equals(txtCiuC.getText())|| !"".equals(txtCPC.getText())|| !"".equals(txtPaisC.getText())|| !"".equals(txtEstC.getText())|| !"".equals(txtTelC.getText())|| !"".equals(txtCorreoC.getText())){
            
             cl.setApellidop(txtAPC.getText());
                cl.setApellidom(txtAMC.getText());
                cl.setNombre(txtNomC.getText());
                cl.setCalle(txtCalleC.getText());
                 cl.setColonia(txtColC.getText());
                cl.setCiudad(txtCiuC.getText());
                cl.setPais(txtPaisC.getText());
                cl.setEstado(txtEstC.getText());
                cl.setCorreo(txtCorreoC.getText());
                client.RegistrarCliente(cl);
                JOptionPane.showMessageDialog(null, "CLIENTE REGISTRADO");
           }else{
             JOptionPane.showMessageDialog(null, "LOS CAMPOS ESTAN VACÍOS");
          
         } 
    }//GEN-LAST:event_btnGuardarCActionPerformed

    private void btnGuardarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnGuardarCMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JTable TableCliente;
    private javax.swing.JTable TableProducto;
    private javax.swing.JTable TableProveedor;
    private javax.swing.JTable TableVenta;
    private javax.swing.JTable TableVentas;
    private javax.swing.JButton btnActualizarC;
    private javax.swing.JButton btnActualizarEmp;
    private javax.swing.JButton btnActualizarPro;
    private javax.swing.JButton btnActualizarProduc;
    private javax.swing.JButton btnEliminarC;
    private javax.swing.JButton btnEliminarPro;
    private javax.swing.JButton btnEliminarProduc;
    private javax.swing.JButton btnEliminarVenta;
    private javax.swing.JButton btnExcelProduc;
    private javax.swing.JButton btnGenerarVenta;
    private javax.swing.JButton btnGuardarC;
    private javax.swing.JButton btnGuardarPro;
    private javax.swing.JButton btnGuardarProduc;
    private javax.swing.JButton btnNuevoC;
    private javax.swing.JButton btnNuevoPro;
    private javax.swing.JButton btnNuevoProduc;
    private javax.swing.JButton btnPDFVentas;
    private javax.swing.JButton btnRegistrarUsu;
    private javax.swing.JComboBox<String> cbProvedorProduc;
    private javax.swing.JComboBox<String> cbRolUsu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField txtAMC;
    private javax.swing.JTextField txtAMUsu;
    private javax.swing.JTextField txtAPC;
    private javax.swing.JTextField txtAPUsu;
    private javax.swing.JTextField txtCPC;
    private javax.swing.JTextField txtCPEmp;
    private javax.swing.JTextField txtCPPRO;
    private javax.swing.JTextField txtCalleC;
    private javax.swing.JTextField txtCalleEmp;
    private javax.swing.JTextField txtCallePro;
    private javax.swing.JTextField txtCanProduc;
    private javax.swing.JTextField txtCantidadVenta;
    private javax.swing.JTextField txtCiuC;
    private javax.swing.JTextField txtCiuEmp;
    private javax.swing.JTextField txtCiuPro;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCodEmp;
    private javax.swing.JTextField txtCodPro;
    private javax.swing.JTextField txtCodProduc;
    private javax.swing.JTextField txtCodVentaCliente;
    private javax.swing.JTextField txtCodigoVenta;
    private javax.swing.JTextField txtColC;
    private javax.swing.JTextField txtColEmp;
    private javax.swing.JTextField txtColPro;
    private javax.swing.JTextField txtContraseñaUsu;
    private javax.swing.JTextField txtCorreoC;
    private javax.swing.JTextField txtCorreoUsu;
    private javax.swing.JTextField txtDescripcionVenta;
    private javax.swing.JTextField txtEmpresaPro;
    private javax.swing.JTextField txtEstC;
    private javax.swing.JTextField txtEstadoEmp;
    private javax.swing.JTextField txtEstadoPro;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtMenEmp;
    private javax.swing.JTextField txtNomC;
    private javax.swing.JTextField txtNomClienteVenta;
    private javax.swing.JTextField txtNomEmp;
    private javax.swing.JTextField txtNomProduc;
    private javax.swing.JTextField txtNomUsu;
    private javax.swing.JTextField txtNumC;
    private javax.swing.JTextField txtNumEmp;
    private javax.swing.JTextField txtNumPro;
    private javax.swing.JTextField txtPaisC;
    private javax.swing.JTextField txtPaisEmp;
    private javax.swing.JTextField txtPaisPro;
    private javax.swing.JTextField txtPrecioProduc;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtStockDisponible;
    private javax.swing.JTextField txtTelC;
    private javax.swing.JTextField txtTelEmp;
    private javax.swing.JTextField txtTelPro;
    // End of variables declaration//GEN-END:variables
}
