/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg20151578099_20191578005;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author aulasingenieria
 */
public class FormularioUsuarios extends javax.swing.JFrame {
    
    
    // Variables

    /**
     *
     */
    public Vector<ProcesosUsuario> usuarios;  


    /**
     * Creates new form FormularioUsuarios
     */
    public FormularioUsuarios() {
        usuarios = new Vector<ProcesosUsuario>();

        initComponents();
        
        this.setTitle("Formulario de Usuarios");

        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
            }
        ));




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        comboDeporte = new javax.swing.JComboBox<>();
        botonAdicionar = new javax.swing.JButton();
        txtIdentificacion = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        radioHombre = new javax.swing.JRadioButton();
        radioMujer = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTotalHombres = new javax.swing.JTextField();
        txtTotalFuAtCi = new javax.swing.JTextField();
        txtTotalMujeres = new javax.swing.JTextField();
        txtTotalOtros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuarios - Empresa DataCenter S.A.");

        jLabel2.setText("Nro. Identificacion:");

        jLabel3.setText("Nombre Usuario:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Genero:");

        jLabel6.setText("Deporfe Favorito:");

        comboDeporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Futbol", "Ciclismo", "Atletismo", "Otro" }));

        botonAdicionar.setText("Adicionar Usuario");
        botonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdicionarActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioHombre);
        radioHombre.setText("Hombre");

        buttonGroup1.add(radioMujer);
        radioMujer.setText("Mujer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAdicionar)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioHombre)
                        .addGap(18, 18, 18)
                        .addComponent(radioMujer)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioHombre)
                        .addComponent(radioMujer)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonAdicionar)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Usuario", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Total Hombres:");

        jLabel8.setText("Total Futbol, Atletismo, Ciclismo");

        jLabel9.setText("Total Mujeres");

        jLabel10.setText("Total Otros Deportes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotalHombres, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(txtTotalFuAtCi))
                .addGap(108, 108, 108)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotalMujeres)
                    .addComponent(txtTotalOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(txtTotalHombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtTotalFuAtCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );

        jTabbedPane1.addTab("Consultar Usuarios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    
    // Variables
    // private Vector<ProcesosUsuario> usuarios;  
    /*

    ProcesosUsuario(String genero, String deporte, String identificacion, String nombre, int edad);
        

    */
    private void botonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdicionarActionPerformed
        // TODO add your handling code here:
        // Validar los campos de texto
        if( txtIdentificacion.getText().equals("") || txtUsuario.getText().equals("") || txtEdad.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
            return;
        }
        // Validar RadioButtons
        if(!(radioHombre.isSelected() || radioMujer.isSelected())){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un genero");
            return;
        }
        String genero = "";
        if(radioHombre.isSelected()){
            genero = "Hombre";
        }else{
            genero = "Mujer";
        }
        // Validar ComboBox
        if(comboDeporte.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un deporte");
            return;
        }
        String deporte = "";
        switch(comboDeporte.getSelectedIndex()){
            case 1:
                deporte = "Futbol";
                break;
            case 2:
                deporte = "Ciclismo";
                break;
            case 3:
                deporte = "Atletismo";
                break;
            case 4:
                deporte = "Otros";
                break;
        }        
        // Validar que el usuario no exista
        if(usuarios.contains(new ProcesosUsuario(genero, comboDeporte.getSelectedItem().toString(), txtIdentificacion.getText(), txtUsuario.getText(), Integer.parseInt(txtEdad.getText())))){
            JOptionPane.showMessageDialog(null, "El usuario ya existe");
            return;
        }
        // Adicionar el usuario
        usuarios.add(new ProcesosUsuario(genero, comboDeporte.getSelectedItem().toString(), txtIdentificacion.getText(), txtUsuario.getText(), Integer.parseInt(txtEdad.getText())));
        // Limpiar los campos de texto
        txtIdentificacion.setText("");
        txtUsuario.setText("");
        txtEdad.setText("");
        // Limpiar los RadioButtons
        radioHombre.setSelected(false);
        radioMujer.setSelected(false);
        // Limpiar los ComboBox
        comboDeporte.setSelectedIndex(0);

        // Actualizar la tabla
        actualizarTabla();

        // Actualizar los totales
        actualizarTotales();
        
    }//GEN-LAST:event_botonAdicionarActionPerformed

 public void actualizarTabla(){
        // Encabezados: Cedula	Cliente	Edad	Salario	Deporte
        String encabezados[] = {"Genero", "Deporte", "Identificacion", "Usuario", "Edad"};
        String datos[][] = new String[usuarios.size()][5];
        for(int i = 0; i < usuarios.size(); i++){
            datos[i][0] = usuarios.get(i).getGenero();
            datos[i][1] = usuarios.get(i).getDeporte();
            datos[i][2] = usuarios.get(i).getIdentificacion();
            datos[i][3] = usuarios.get(i).getNombre();
            datos[i][4] = String.valueOf(usuarios.get(i).getEdad());
        }
        // Limpiar la tabla
        jTable1.setModel(new javax.swing.table.DefaultTableModel(datos, encabezados));
    }

    // Totales
    public void actualizarTotales(){
        // Total de usuarios hombres
        int totalHombres = 0;
        // Total de usuarios mujeres
        int totalMujeres = 0;
        // Total de usuarios de cada deporte
        int totalFuAtCi = 0;
        // Total otros deportes
        int totalOtros = 0;

        // Recorrer los usuarios
        for(int i = 0; i < usuarios.size(); i++){
            // Si es hombre
            if(usuarios.get(i).getGenero().equals("Hombre")){
                totalHombres++;
            }else{
                totalMujeres++;
            }
            // Si es de fuerza atletica
            if(usuarios.get(i).getDeporte().equals("Futbol") || usuarios.get(i).getDeporte().equals("Ciclismo")){
                totalFuAtCi++;
            }else{
                totalOtros++;
            }
            
        }

        // Actualizar los totales
        txtTotalHombres.setText(String.valueOf(totalHombres));
        txtTotalMujeres.setText(String.valueOf(totalMujeres));
        txtTotalFuAtCi.setText(String.valueOf(totalFuAtCi));
        txtTotalOtros.setText(String.valueOf(totalOtros));
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdicionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboDeporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radioHombre;
    private javax.swing.JRadioButton radioMujer;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtTotalFuAtCi;
    private javax.swing.JTextField txtTotalHombres;
    private javax.swing.JTextField txtTotalMujeres;
    private javax.swing.JTextField txtTotalOtros;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
