/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Controlador.ControladorGUI;
import Modelo.Cliente;
import Utilidades.Render;

/**
 *
 * @author melig
 */
public class Clientes extends javax.swing.JFrame {

    // ControladorGUI
    private ControladorGUI controladorGUI;

    /**
     * Creates new form Clientes
     * @param controladorGUI
     */
    public Clientes(ControladorGUI controladorGUI) {
        this.controladorGUI = controladorGUI;
        initComponents();

        // Actualizar tabla
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalTabs = new javax.swing.JTabbedPane();
        panelConsultar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        panelIngresar = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // panelConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
        //     public void mouseClicked(java.awt.event.MouseEvent evt) {
        //         panelConsultarMouseClicked(evt);
        //     }
        // });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout panelConsultarLayout = new javax.swing.GroupLayout(panelConsultar);
        panelConsultar.setLayout(panelConsultarLayout);
        panelConsultarLayout.setHorizontalGroup(
            panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConsultarLayout.setVerticalGroup(
            panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        principalTabs.addTab("Consultar", panelConsultar);

        lblUsuario.setText("Usuario:");

        lblIdentificacion.setText("Identificaci�n");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre Completo");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblEdad.setText("Edad");

        lblDireccion.setText("Direccion de localizac�on");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIngresarLayout = new javax.swing.GroupLayout(panelIngresar);
        panelIngresar.setLayout(panelIngresarLayout);
        panelIngresarLayout.setHorizontalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addGroup(panelIngresarLayout.createSequentialGroup()
                        .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdentificacion)
                            .addComponent(lblNombre)
                            .addComponent(lblEdad)
                            .addComponent(lblDireccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addContainerGap())
        );
        panelIngresarLayout.setVerticalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacion)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        principalTabs.addTab("Ingresar", panelIngresar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        // Exportaciones e = new Exportaciones();
        // e.setVisible(true);

        // Validar Campos
        // txtID
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo ID no puede estar vacio");
            txtId.requestFocus();
            return;
        } else {
            if (txtId.getText().length() != 10) {
                JOptionPane.showMessageDialog(null, "El campo ID no puede tener mas o menos de 10 caracteres");
                txtId.requestFocus();
                return;
            }
        }

        // txtNombre
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Nombre no puede estar vacio");
            txtNombre.requestFocus();
            return;
        } else {
            if (txtNombre.getText().length() > 50) {
                JOptionPane.showMessageDialog(null, "El campo Nombre no puede tener mas de 50 caracteres");
                txtNombre.requestFocus();
                return;
            }
        }

        // txtEdad
        if (txtEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Edad no puede estar vacio");
            txtEdad.requestFocus();
            return;
        } else {
            if (Integer.parseInt(txtEdad.getText()) < 18 || Integer.parseInt(txtEdad.getText()) > 100) {
                JOptionPane.showMessageDialog(null, "El campo Edad no puede ser menor de 18 o mayor de 100");
                txtEdad.requestFocus();
                return;
            }
        }

        // txtDireccion
        if (txtDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Direccion no puede estar vacio");
            txtDireccion.requestFocus();
            return;
        } else {
            if (txtDireccion.getText().length() > 50) {
                JOptionPane.showMessageDialog(null, "El campo Direccion no puede tener mas de 50 caracteres");
                txtDireccion.requestFocus();
                return;
            }
        }

        // Crear un nuevo cliente
        Cliente c = new Cliente();
        c.setIdentificacion(txtId.getText());
        c.setNombre(txtNombre.getText());
        c.setEdad(Integer.parseInt(txtEdad.getText()));
        c.setDireccion(txtDireccion.getText());
        
        // Agregar el cliente a la lista
        controladorGUI.agregarCliente(c);

        // Actualizar la tabla
        actualizarTabla();

        // Limpiar el formulario
        txtId.setText("");
        txtNombre.setText("");
        txtEdad.setText("");
        txtDireccion.setText("");

        // Mostrar el panel de la tabla
        principalTabs.setSelectedIndex(0);


    }//GEN-LAST:event_btnIngresarActionPerformed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        // TODO add your handling code here:
        int columna = tblClientes.getColumnModel().getColumnIndexAtX(evt.getX());
        int fila = evt.getY() / tblClientes.getRowHeight();

        if(fila < tblClientes.getRowCount() && fila >= 0 && columna < tblClientes.getColumnCount() && columna >= 0){
            Object value = tblClientes.getValueAt(fila, columna);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                // Eliminar
                if(boton.getText().equals("Eliminar")){
                    int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar el cliente?", "Eliminar Cliente", JOptionPane.YES_NO_OPTION);
                    if(respuesta == JOptionPane.YES_OPTION){
                        if(controladorGUI.eliminarCliente(controladorGUI.listarClientes().get(fila).getIdentificacion())){
                            JOptionPane.showMessageDialog(null, "El cliente fue eliminado correctamente.", "Cliente Eliminado", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "El cliente NO fue eliminado, porque tiene exportaciones aprobadas.", "Cliente NO puede ser Eliminado", JOptionPane.ERROR_MESSAGE);
                        }
                        actualizarTabla();
                    }
                }
                // Exportaciones
                if(boton.getText().equals("Exportaciones")){
                    controladorGUI.mostrarExportaciones(controladorGUI.listarClientes().get(fila).getIdentificacion());
                }
            }
        }
    }//GEN-LAST:event_tablaClientesMouseClicked

    // Actualizar la tabla
    private void actualizarTabla() {

        tblClientes.setDefaultRenderer(Object.class, new Render());

        // Encabezados
        String[] encabezados = {"Identificacion", "Nombre", "Edad", "Direccion", "No. Exportaciones", "Eliminar", "Exportaciones"};

        // Limpiar la tabla
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);

        // Agregar encabezados
        modelo.setColumnIdentifiers(encabezados);

        // Recorrer la lista de clientes
        for (Cliente c : controladorGUI.listarClientes()) {
            // Numero de exportaciones del cliente
            int nExportaciones = controladorGUI.nExportaciones(c.getIdentificacion());
            // Boton eliminar
            JButton btnEliminar = new javax.swing.JButton("Eliminar");
            // Boton exportaciones
            JButton btnExportaciones = new javax.swing.JButton("Exportaciones");
            Object[] fila = {c.getIdentificacion(), c.getNombre(), c.getEdad(), c.getDireccion(), nExportaciones, btnEliminar, btnExportaciones};
            modelo.addRow(fila);
        }
        tblClientes.setRowHeight(25);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelConsultar;
    private javax.swing.JPanel panelIngresar;
    private javax.swing.JTabbedPane principalTabs;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
