/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package punto2_S_GR;

import java.util.ArrayList;

/**
 *
 * @author User
 */
public class Consultas extends javax.swing.JFrame {

    private ArrayList<Software> software;
    /**
     * Creates new form Consultas
     */
    public Consultas(ArrayList<Software> software) {
        this.software = software;
        initComponents();
        // Buscar cual tiene mayor promedio si Entretenimiento o Laboral
        double promE = 0;
        int cantE = 0;
        double promL = 0;
        int cantL = 0;
        double mayorE = 0;
        int indiceE = -1;
        int count = 0;
        // Suma
        for(Software s : software){
            if(s.getCategoria().equals("E")){
                cantE++;
                promE+=s.getRam();
                
                if(s.getRam()>mayorE){
                    indiceE = count;
                    mayorE = s.getRam();
                }
                
            } else if(s.getCategoria().equals("L")) {
                cantL++;
                promL+=s.getRam();
            }
            count++;
        }        
        
        if(cantE!=0)
            promE/=cantE;
        if(cantL!=0)
            promL/=cantL;
        
        if(promE<promL)
            lblPromedio.setText("Laboral");
        else if(promE>promL)
            lblPromedio.setText("Entretenimiento");
        else
            lblPromedio.setText("Iguales");
        
        if(indiceE!=-1)
            lblEntretenimiento.setText(software.get(indiceE).getNombre());
        else
            lblEntretenimiento.setText("Ninguno");
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEntretenimiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Informe:");

        jLabel2.setText("Mayor promedio:");

        lblPromedio.setText("jLabel3");

        jLabel4.setText("Mas memoria ram consume en Entretenimiento:");

        lblEntretenimiento.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEntretenimiento)
                            .addComponent(lblPromedio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPromedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEntretenimiento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEntretenimiento;
    private javax.swing.JLabel lblPromedio;
    // End of variables declaration//GEN-END:variables
}
