/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author nitro5
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        menuItemGuardar = new javax.swing.JMenuItem();
        menuTicobingo = new javax.swing.JMenu();
        menuItemNuevoJuego = new javax.swing.JMenuItem();
        menuItemGenerarCartones = new javax.swing.JMenuItem();
        menuItemVenderCartones = new javax.swing.JMenuItem();
        menuItemComenzarBingo = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelHeader.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("TicoBingo");
        panelHeader.add(jLabel2, new java.awt.GridBagConstraints());

        jButton4.setText("Nuevo Juego");
        panelHeader.add(jButton4, new java.awt.GridBagConstraints());

        jButton3.setText("Generar Cartones");
        panelHeader.add(jButton3, new java.awt.GridBagConstraints());

        jButton2.setText("Vender Cartones");
        panelHeader.add(jButton2, new java.awt.GridBagConstraints());

        jButton1.setText("Comenzar Bingo");
        panelHeader.add(jButton1, new java.awt.GridBagConstraints());

        jLabel1.setText("Bolita No");
        panelHeader.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel3.setText("11");
        panelHeader.add(jLabel3, new java.awt.GridBagConstraints());

        jButton5.setText("Nueva Bolita");
        panelHeader.add(jButton5, new java.awt.GridBagConstraints());

        getContentPane().add(panelHeader, new java.awt.GridBagConstraints());

        panelBody.setPreferredSize(new java.awt.Dimension(1000, 450));

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(panelBody, gridBagConstraints);

        menuArchivo.setText("Archivo");

        menuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        menuItemAbrir.setText("Abrir");
        menuArchivo.add(menuItemAbrir);

        menuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, 0));
        menuItemGuardar.setText("Guardar");
        menuArchivo.add(menuItemGuardar);

        menuBar.add(menuArchivo);

        menuTicobingo.setText("TicoBingo");

        menuItemNuevoJuego.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, 0));
        menuItemNuevoJuego.setText("Nuevo Juego");
        menuTicobingo.add(menuItemNuevoJuego);

        menuItemGenerarCartones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, 0));
        menuItemGenerarCartones.setText("Generar Cartones");
        menuTicobingo.add(menuItemGenerarCartones);

        menuItemVenderCartones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, 0));
        menuItemVenderCartones.setText("Vender Cartones");
        menuTicobingo.add(menuItemVenderCartones);

        menuItemComenzarBingo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        menuItemComenzarBingo.setText("Comenzar Bingo");
        menuTicobingo.add(menuItemComenzarBingo);

        menuBar.add(menuTicobingo);

        menuAyuda.setText("Ayuda");

        menuItemAcercaDe.setText("Acerca de");
        menuAyuda.add(menuItemAcercaDe);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAbrir;
    private javax.swing.JMenuItem menuItemAcercaDe;
    private javax.swing.JMenuItem menuItemComenzarBingo;
    private javax.swing.JMenuItem menuItemGenerarCartones;
    private javax.swing.JMenuItem menuItemGuardar;
    private javax.swing.JMenuItem menuItemNuevoJuego;
    private javax.swing.JMenuItem menuItemVenderCartones;
    private javax.swing.JMenu menuTicobingo;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables
}
