/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author nitro5
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtBolita = new javax.swing.JTextField();
        panelBody = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        menuItemGuardar = new javax.swing.JMenuItem();
        menuTicobingo = new javax.swing.JMenu();
        menuItemNuevoJuego = new javax.swing.JMenuItem();
        menuItemGenerarCartones = new javax.swing.JMenuItem();
        menuItemVenderCartones = new javax.swing.JMenuItem();
        menuItemComenzarBingo = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Iconos/Nuevo Juego.png"))); // NOI18N
        jButton4.setText("Nuevo Juego");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelHeader.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 5, -1, 70));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Iconos/Generar Cartones.png"))); // NOI18N
        jButton3.setText("Generar Cartones");
        panelHeader.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 5, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Iconos/Vender Cartones.png"))); // NOI18N
        jButton2.setText("Vender Cartones");
        panelHeader.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 5, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Iconos/Comenzar Bingo.jpg"))); // NOI18N
        jButton1.setText("Comenzar Bingo");
        panelHeader.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 5, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Iconos/Nueva Bolita.png"))); // NOI18N
        jButton5.setText("Nueva Bolita");
        panelHeader.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 5, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Iconos/ticobingo.PNG"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        panelHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 51, 255));
        jLabel24.setText("BOLITA N°");
        panelHeader.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, -1, -1));

        txtBolita.setEditable(false);
        txtBolita.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        txtBolita.setForeground(new java.awt.Color(255, 0, 102));
        txtBolita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelHeader.add(txtBolita, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 71, 48));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 1, 1200, 80));

        panelBody.setAlignmentX(0.0F);
        panelBody.setAlignmentY(0.0F);
        panelBody.setPreferredSize(new java.awt.Dimension(1000, 450));
        panelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, -1));

        menuArchivo.setText("Archivo");

        menuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        menuItemAbrir.setText("Abrir");
        menuArchivo.add(menuItemAbrir);

        menuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, 0));
        menuItemGuardar.setText("Guardar");
        menuArchivo.add(menuItemGuardar);

        menuBar.add(menuArchivo);

        menuTicobingo.setText("TicoBingo");

        menuItemNuevoJuego.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, 0));
        menuItemNuevoJuego.setText("Nuevo Juego");
        menuTicobingo.add(menuItemNuevoJuego);

        menuItemGenerarCartones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, 0));
        menuItemGenerarCartones.setText("Generar Cartones");
        menuTicobingo.add(menuItemGenerarCartones);

        menuItemVenderCartones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, 0));
        menuItemVenderCartones.setText("Vender Cartones");
        menuTicobingo.add(menuItemVenderCartones);

        menuItemComenzarBingo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        menuItemComenzarBingo.setText("Comenzar Bingo");
        menuTicobingo.add(menuItemComenzarBingo);

        menuBar.add(menuTicobingo);

        menuAyuda.setText("Ayuda");

        menuItemAcercaDe.setText("Acerca de");
        menuAyuda.add(menuItemAcercaDe);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAbrir;
    private javax.swing.JMenuItem menuItemAcercaDe;
    private javax.swing.JMenuItem menuItemComenzarBingo;
    private javax.swing.JMenuItem menuItemGenerarCartones;
    private javax.swing.JMenuItem menuItemGuardar;
    private javax.swing.JMenuItem menuItemNuevoJuego;
    private javax.swing.JMenuItem menuItemVenderCartones;
    private javax.swing.JMenu menuTicobingo;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtBolita;
    // End of variables declaration//GEN-END:variables

    // get panel body
    public javax.swing.JPanel getPanelBody() {
        return panelBody;
    }
}
