/*
 * Universidad Estatal a Distancia
Estudiante:Melissa Guadamuz Fernández
Cedula:113870559
Centro Universitario San José
Grupo # 1
Tutor JOSE MANUEL SALAZAR HERRERA
Tarea#1
Primer Cuatrimestre 2022
 */
package Vista;

import Modelo.CargaPesada;
import Modelo.CargaSuelta;
import Modelo.Cotizacion;
import Modelo.Usuario;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author melig
 */
public class ExportaCR extends javax.swing.JFrame {

    private final Usuario usuario;
    /**
     * Creates new form ExportaCR
     */
    public ExportaCR() {
        initComponents();
        
        usuario = new Usuario();
        Id1.setText(usuario.getCotizacion().getId()+"");
        Fec.setText(usuario.getCotizacion().getFecha());
        
        panelPesada.setVisible(false);        
        panelSuelta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Nom = new javax.swing.JTextField();
        Ed = new javax.swing.JTextField();
        Dir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Id1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Fec = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Kg2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Cns = new javax.swing.JRadioButton();
        Cnoc = new javax.swing.JRadioButton();
        Cso = new javax.swing.JRadioButton();
        Mon = new javax.swing.JRadioButton();
        Pac = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Ni = new javax.swing.JRadioButton();
        En = new javax.swing.JTextField();
        Am = new javax.swing.JRadioButton();
        As = new javax.swing.JRadioButton();
        Cno = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CotizacionDatos = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Suelta = new javax.swing.JRadioButton();
        Pesada = new javax.swing.JRadioButton();
        panelPesada = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TipoServicioSuelta = new javax.swing.JComboBox<>();
        PiesCargaSuelta = new javax.swing.JTextField();
        panelSuelta = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        TipoCargaPesada = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        PiesContenedorPesada = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        TipoServicioPesada = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Identificación");

        jLabel2.setText("Nombre Completo");

        jLabel3.setText("Edad");

        jLabel4.setText("Direccion de localizacíon");

        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });

        Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomActionPerformed(evt);
            }
        });

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Id de cotización:");

        Id1.setText("Id de cotización");

        jLabel6.setText("Fecha de cotización:");

        Fec.setText("Fecha de cotización");

        jLabel7.setText("kilogramos a exportar:");

        Kg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kg2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Usuario:");

        jLabel9.setText("Cotizacion:");

        buttonGroup1.add(Cns);
        Cns.setText("Centro Sur Oriental (Kentucky, Tennessee, Alabama, Misisipi) ");

        buttonGroup1.add(Cnoc);
        Cnoc.setText("Centro Norte Occidental (Minnesota, Dakota del Norte, Dakota del Sur, Iowa,  Nebraska, Misuri, Kansas)");
        Cnoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnocActionPerformed(evt);
            }
        });

        buttonGroup1.add(Cso);
        Cso.setText(" Centro Sur Occidental (Arkansas, Oklahoma, Texas, Luisiana) ");

        buttonGroup1.add(Mon);
        Mon.setText("Montaña (Montana, Idaho, Wyoming, Colorado, Utah, Nevada, Arizona,  Nuevo México)");
        Mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonActionPerformed(evt);
            }
        });

        buttonGroup1.add(Pac);
        Pac.setText("Pacífico (Alaska, Washington, Oregón, California, Hawái).");
        Pac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacActionPerformed(evt);
            }
        });

        jLabel10.setText("Zona de la Exportación (9 Zonas):");

        jLabel11.setText("Dirección de entrega:");

        buttonGroup1.add(Ni);
        Ni.setText("Nueva Inglaterra (Maine, Nuevo Hampshire, Vermont, Massachusetts,  Connecticut, Rhode Island)");
        Ni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NiActionPerformed(evt);
            }
        });

        En.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnActionPerformed(evt);
            }
        });

        buttonGroup1.add(Am);
        Am.setText("Atlántico Medio (Nueva York, Pensilvania, Nueva Jersey)");
        Am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmActionPerformed(evt);
            }
        });

        buttonGroup1.add(As);
        As.setText("Atlántico Sur (Maryland, Delaware, Virginia Occidental, Virginia, Carolina del  Norte, Carolina del Sur, Georgia, Florida)");
        As.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsActionPerformed(evt);
            }
        });

        buttonGroup1.add(Cno);
        Cno.setText("Centro Norte Oriental (Michigan, Wisconsin, Illinois, Indiana, Ohio)");

        jLabel12.setText("Resultado:");

        Resultado.setText("Resultado");

        jLabel13.setText("Datos Cliente:");

        Cliente.setText("Cliente");

        jLabel14.setText("Datos Cotizacion:");

        CotizacionDatos.setText("Cotizacion");

        jLabel15.setText("Carga:");

        buttonGroup2.add(Suelta);
        Suelta.setText("Suelta");
        Suelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SueltaActionPerformed(evt);
            }
        });

        buttonGroup2.add(Pesada);
        Pesada.setText("Pesada");
        Pesada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesadaActionPerformed(evt);
            }
        });

        panelPesada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setText("Pies de Carga:");

        jLabel17.setText("Tipo de Servicio:");

        TipoServicioSuelta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Barco", "Avion" }));

        javax.swing.GroupLayout panelPesadaLayout = new javax.swing.GroupLayout(panelPesada);
        panelPesada.setLayout(panelPesadaLayout);
        panelPesadaLayout.setHorizontalGroup(
            panelPesadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TipoServicioSuelta, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPesadaLayout.createSequentialGroup()
                        .addGroup(panelPesadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(PiesCargaSuelta))
                .addContainerGap())
        );
        panelPesadaLayout.setVerticalGroup(
            panelPesadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PiesCargaSuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoServicioSuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        panelSuelta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("Tipo de Carga:");

        TipoCargaPesada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Contenedor Refrigerado", "Contenedor NO Refrigerado", "Carga Embalada" }));
        TipoCargaPesada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCargaPesadaActionPerformed(evt);
            }
        });

        jLabel23.setText("Tipo de Servicio:");

        PiesContenedorPesada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "20", "40" }));

        jLabel24.setText("Pies del Contenedor:");

        TipoServicioPesada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Barco", "Avion" }));

        javax.swing.GroupLayout panelSueltaLayout = new javax.swing.GroupLayout(panelSuelta);
        panelSuelta.setLayout(panelSueltaLayout);
        panelSueltaLayout.setHorizontalGroup(
            panelSueltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSueltaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSueltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TipoCargaPesada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSueltaLayout.createSequentialGroup()
                        .addGroup(panelSueltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addComponent(TipoServicioPesada, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PiesContenedorPesada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSueltaLayout.setVerticalGroup(
            panelSueltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSueltaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoCargaPesada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoServicioPesada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PiesContenedorPesada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Nom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                    .addComponent(Id)
                                    .addComponent(Dir, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(Kg2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel10))
                            .addComponent(jButton1)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Id1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fec)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Cso))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Cnoc))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Cns))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Cno))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(As))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Am))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Ni))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Pac))
                            .addComponent(Cliente)
                            .addComponent(jLabel14)
                            .addComponent(CotizacionDatos)
                            .addComponent(jLabel12)
                            .addComponent(Resultado)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(En, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Mon)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Pesada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Suelta))
                            .addComponent(panelSuelta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelPesada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suelta)
                    .addComponent(Pesada))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Dir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Id1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Fec))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Kg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(Ni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Am)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(As)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cns)
                        .addGap(8, 8, 8)
                        .addComponent(Cnoc))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPesada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pac)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(En, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cliente)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CotizacionDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Resultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed

                // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //  informacion que se le solcitada al cliente:
        String nombre;
        String identificacion;
        int edad = -1;
        String direccion;
        boolean valido = true;
        
        try{
            identificacion = Id.getText();
            nombre = Nom.getText();
            edad = Integer.parseInt(Ed.getText());
            direccion = Dir.getText();
            if(!(identificacion.length()==10))
                valido = false;

            if(!(nombre.length()< 50))
                valido =false;

            if(!(edad >18 && edad < 100))
                valido = false;

            if (!(direccion.length()>= 20))
                valido = false;

            double kilogramos = Double.parseDouble(Kg2.getText());

            if(!(kilogramos >=1))
                valido = false;

            // Aqui se valida solamente un boton a seleccionar para la zona de exportancion
            Cotizacion c = usuario.getCotizacion();
            String direccion2 = En.getText();
            if (Ni.isSelected())
                c.setZona("Nueva Inglaterra");
            else if (Am.isSelected())
                c.setZona("Atlántico Medio");
            else if (As.isSelected())
                c.setZona("Atlántico Sur");
            else if (Cno.isSelected())
                c.setZona("Centro Norte Oriental");
            else if (!Cns.isSelected())
                c.setZona("Centro Sur Oriental");
            else if (!Cnoc.isSelected())
                c.setZona("Centro Norte Occidental");
            else if (!Cso.isSelected())
                c.setZona("Centro Sur Occidental");
            else if (!Mon.isSelected())
                c.setZona("Montaña");
            else if (!Pac.isSelected())
                c.setZona("Pacifico");
            else
                valido = false;

            if(!(direccion2.length()>= 20))
                valido = false;
            
            if(Pesada.isSelected()){
                // Validar Carga Pesada
                CargaPesada cp = new CargaPesada(c);
                
                // Tipo de Carga
                switch (TipoCargaPesada.getSelectedIndex()) {
                    case 1:
                        cp.setTipoCarga("Contenedor Refrigerado");
                        break;
                    case 2:
                        cp.setTipoCarga("Contenedor no refrigerado");
                        break;
                    case 3:
                        cp.setTipoCarga("Carga embalada");
                        break;
                    default:
                        valido = false;
                        break;
                }
                // Tipo de servicio true: Barco, false: Avion
                switch (TipoServicioPesada.getSelectedIndex()) {
                    case 1:
                        cp.setTipoServicio(true);
                        break;
                    case 2:
                        cp.setTipoServicio(false);
                        break;
                    default:
                        valido = false;
                        break;
                }
                // Pies del contenedor
                switch (PiesContenedorPesada.getSelectedIndex()) {
                    case 1:
                        cp.setPiesContenedor(true);
                        break;
                    case 2:
                        cp.setPiesContenedor(false);
                        break;
                    default:
                        valido = false;
                        break;
                }

                if (valido)
                    c = cp;                
            } else if(Suelta.isSelected()){                
                // Validar Carga Suelta
                CargaSuelta cs = new CargaSuelta(c);
                // Pies de Carga
                if(PiesCargaSuelta.getText().equals(""))
                    valido = false;
                else
                    cs.setPiesCarga(Double.parseDouble(PiesCargaSuelta.getText()));
                
                // Tipo de servicio true: Barco, false: Avion
                switch (TipoServicioSuelta.getSelectedIndex()) {
                    case 1:
                        cs.setTipoServicio(true);
                        break;
                    case 2:
                        cs.setTipoServicio(false);
                        break;
                    default:
                        valido = false;
                        break;
                }
                if (valido)
                    c = cs;
            }
            
            if(valido){
                // Cotizacion
                c.setDireccion(direccion2);
                c.setKg(kilogramos);
                // Usuario
                usuario.setNombre(nombre);
                usuario.setEdad(edad);
                usuario.setDireccion(direccion);
                usuario.setIdentificacion(identificacion);
                usuario.setCotizacion(c);
                // Mostrar Usuario
                Cliente.setText(usuario.datosCliente());
                CotizacionDatos.setText(usuario.getCotizacion().toString());
                Resultado.setText(usuario.getCotizacion().calcularExportacion());
            } else {
                JOptionPane.showMessageDialog(null, "Uno o mas valores ingresados no son validos");
            }
        } catch ( HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Uno o mas valores ingresados no son validos");
        }   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Kg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kg2ActionPerformed

    private void CnocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnocActionPerformed

    private void MonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonActionPerformed

    private void PacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacActionPerformed

    private void NiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NiActionPerformed

    private void EnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnActionPerformed

    private void AmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmActionPerformed

    private void AsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsActionPerformed

    private void PesadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesadaActionPerformed
        // TODO add your handling code here:
        System.out.print("Pesada");        
        panelPesada.setVisible(false);        
        panelSuelta.setVisible(true);
    }//GEN-LAST:event_PesadaActionPerformed

    private void SueltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SueltaActionPerformed
        // TODO add your handling code here:
        System.out.print("Suelta");
        panelPesada.setVisible(true);        
        panelSuelta.setVisible(false);
    }//GEN-LAST:event_SueltaActionPerformed

    private void TipoCargaPesadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCargaPesadaActionPerformed
        // TODO add your handling code here:
        if(TipoCargaPesada.getSelectedIndex()!=3){
            TipoServicioPesada.setEnabled(false);
            TipoServicioPesada.setSelectedIndex(1);            
            PiesContenedorPesada.setEnabled(true);
        } else {            
            TipoServicioPesada.setEnabled(true);
            TipoServicioPesada.setSelectedIndex(0);
            PiesContenedorPesada.setEnabled(false);
            PiesContenedorPesada.setSelectedIndex(0);            
        }
    }//GEN-LAST:event_TipoCargaPesadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Am;
    private javax.swing.JRadioButton As;
    private javax.swing.JLabel Cliente;
    private javax.swing.JRadioButton Cno;
    private javax.swing.JRadioButton Cnoc;
    private javax.swing.JRadioButton Cns;
    private javax.swing.JLabel CotizacionDatos;
    private javax.swing.JRadioButton Cso;
    private javax.swing.JTextField Dir;
    private javax.swing.JTextField Ed;
    private javax.swing.JTextField En;
    private javax.swing.JLabel Fec;
    private javax.swing.JTextField Id;
    private javax.swing.JLabel Id1;
    private javax.swing.JTextField Kg2;
    private javax.swing.JRadioButton Mon;
    private javax.swing.JRadioButton Ni;
    private javax.swing.JTextField Nom;
    private javax.swing.JRadioButton Pac;
    private javax.swing.JRadioButton Pesada;
    private javax.swing.JTextField PiesCargaSuelta;
    private javax.swing.JComboBox<String> PiesContenedorPesada;
    private javax.swing.JLabel Resultado;
    private javax.swing.JRadioButton Suelta;
    private javax.swing.JComboBox<String> TipoCargaPesada;
    private javax.swing.JComboBox<String> TipoServicioPesada;
    private javax.swing.JComboBox<String> TipoServicioSuelta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelPesada;
    private javax.swing.JPanel panelPesada1;
    private javax.swing.JPanel panelSuelta;
    // End of variables declaration//GEN-END:variables

}
